### ISSUE TITLE
Need description for the following in PUF_detailed

### ISSUE THREAD

**Issue by eashwarsiddharth** [sagitechls/SSN_SACE_2017_Jan#16]
- average_medicare_allowed_amt
- average_medicare_payment_amt
- average_medicare_standard_amt

How is average_submitted_chrg_amt calculated ?
- Is it the average for a particular(doc_id,city,state,hcpcs_code) ?

**Comment by Rajhan** [comment]
Consider only the Medicare allowed amount since it's the maximum amount a doc can get from Medicare for the services he has rendered irrespective of how much he has charged for the service. average medicare payment amount is the actual amount he has received for the service. The standard amount is the amount Medicare pays for the services to similar docs for the same procedure in similar city and state.

**Comment by eashwarsiddharth** [comment]
@Rajhan is there any specific reason as to why the allowed and payment amounts have a difference ?
- If the doc_id is allowed a certain amt and they have submitted a charge exceeding this amount, then why do they receive a payment that is less than the allowed amount ?
- Is it because some of the claims were rejected due to the patient's medicare constraints  ?
- If so, then the proportion of amount that was rejected could play an important role in profiling the doc_id. Right ?

**Comment by Rajhan** [comment]
medicare as some formulae to determine the amount a doc gets for the services he rendered. Medicare does some bargaining depending on various factors, they have a long list of rules and guidelines which were converted into an act also.
