### ISSUE TITLE
Drug Prescription v/s Drug Hcpcs Code

### ISSUE THREAD

**Issue by eashwarsiddharth** [sagitechls/SSN_SACE_2017_Jan#29]
@Rajhan , I have noticed that in a lot of instances the number_of_drug_hcpcs is NA or 0, but, the doc_id seems to be prescribing drugs(top1:5). Even the med related attributes like number_of_med_hcpcs and the corresponding amount attributes also seem to be NA in such a case.
Eg - doc_id = AB3895583

Could you please share some insight on this ?
I can't seem to understand the reason behind both the NA and the 0.
Is there a reason behind a NA in the attribute ?
- The description doesn't elaborate on that.

If you are considering Avonex v/s Copaxone prescribers, nearly 26% of values in the following attributes seem to have NAs (all attributes have equal number of NAs):
- number_of_drug_hcpcs
- total_drug_services
- total_drug_medicare_allowed_amt
- number_of_med_hcpcs
- total_med_services
- total_med_medicare_allowed_amt

**Comment by Rajhan** [comment]
The basic difference between prescription and any services(medical and drug services from PUF ) is:
The prescription data is a list of drugs the doc wrote for his patients.
The PUF data describes the services the doc has given for his/her patients. drug services are like administering or putting an injection, vaccine etc. medical services are like performing a procedure or an operation. Even if a doc has prescribed many drugs, he may or may not give a drug level services.


Regarding NA's in the services column.
I didn't give you drug and medical level suppresses indicator (flag) column.  please refer the pdf document for the description of the flags columns.

Third, you can take the total number of services instead of drug or medical level services.
